### ISSUE TITLE
Different access for different groups of users

### ISSUE THREAD

**Issue by imthecritic** [dgore7/knowledge-management#7]

**Comment by operant** [comment]
Simple numeric field for a "rank" could provide this functionality. Definitions of the ranks could then either be stored in the DB or in files. Maybe a simple window to create and delete ranks?

**Comment by dgore7** [comment]
talked to @asyed2 and Jose about this. We thought about having three levels of permission. Repos for personal files, repos for groups, and a universal repo. we would allow users to create group repos where they can add members. when uploading a file, a user would specify the level of permission the file should have.

**Comment by operant** [comment]
Also "done to hell"
