### ISSUE TITLE
Develop a high level design of the system

### ISSUE THREAD

**Issue by imthecritic** [dgore7/knowledge-management#8]

**Comment by operant** [comment]
Creating an API class for both clients and server. Possibly add a function so we can get the API spec from the server? If not that, then maybe conflict checking with a priority being assigned to the values in the server's configuration.

**Comment by dgore7** [comment]
The controllers are meant expose our API to the user. The protocol details are in the RequestHandler class in the server, and the Client class on the client side.

**Comment by imthecritic** [comment]
Submitted pdf version to DropBox
